---
Description: Creates an Ubuntu 16.04 Web Server

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0cff7528ff583bf9a
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref WebserverSecurityGroup
      Tags:
        - Key: Project
          Value: udacity
      KeyName: udacity

  WebserverSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: hello-world-webserver
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 3000
          IpProtocol: tcp
          ToPort: 3000
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
Outputs:
  HelloWorldURL:
    Description: The url pointing to our page.
    Value: !Sub "http://${EC2Instance.PublicIp}"
