AWSTemplateFormatVersion: 2010-09-09
Description: Udacity-Prometheus
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: prometheus
      ImageId: 'ami-052efd3df9dad4825'
      InstanceType: t2.micro
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

        - CidrIp: 0.0.0.0/0
          FromPort: 9090
          Description: 'Prometheus'
          IpProtocol: tcp
          ToPort: 9090

        - CidrIp: 0.0.0.0/0
          FromPort: 9001
          Description: 'Prometheus Node exporter'
          IpProtocol: tcp
          ToPort: 9001

        - CidrIp: 0.0.0.0/0
          FromPort: 9093
          Description: 'Alertmanager'
          IpProtocol: tcp
          ToPort: 9093